version: "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  movie_mongodb:
    networks:
      - backend
    image: mongo:latest
    container_name: movie_mongodb
    ports:
      - 27017:27017
  movie-app:
    networks:
      - backend
    image: my-app-image
    container_name: movie-app
    environment:
      - MONGO_HOST=movie_mongodb
    ports:
      - 8080:8080
    links:
      - movie_mongodb